# Generated by Django 2.1.7 on 2019-04-04 00:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='probando',
            field=models.BooleanField(default=True),
        ),
    ]
